# Generated by Django 5.2.6 on 2025-09-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cycle_type', models.CharField(choices=[('70hrs/8days', '70 Hours/8 Days')], default='70hrs/8days', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('driving_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rest_stop', models.BooleanField(default=False)),
                ('fueling_stop', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.trip')),
            ],
        ),
    ]
